// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huikwuzrffgkyspfryxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aWt3dXpyZmZna3lzcGZyeXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDg5NzcsImV4cCI6MjA3NDYyNDk3N30.Em-pbZfPjs52iQqxM49TKAbvwy7ewYBiPzLs8vSQwv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});